# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TravelWise

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://travelwise.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f7c5664b99284ac9b8378e18ae2dccaf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_dc6d7843268e4734a480536c3f270dcc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./Gui
        push: true
        tags: travelwise.azurecr.io/travelwise.gui:${{ github.sha }}
        file: ./Gui/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TravelWise'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a50e4033f0f0458688ed93d4449a75f7 }}
        images: 'travelwise.azurecr.io/travelwise.gui:${{ github.sha }}'